defaults:
  - _self_

name: robotwin_atm_diffusion
_target_: diffusion_policy.workspace.train_robotwin_atm_workspace.TrainRoboTwinATMWorkspace

experiment: ???
horizon: 16
n_obs_steps: 3
n_action_steps: 8
obs_as_global_cond: true

shape_meta: &shape_meta
  obs:
    head_cam:
      shape: [3, 240, 320]
      type: rgb
    agent_pos:
      shape: [16]
      type: low_dim
  action:
    shape: [16]

task:
  dataset:
    _target_: diffusion_policy.dataset.robotwin_atm_image_dataset.RoboTwinATMImageDataset
    train_dataset_dirs: ???
    val_dataset_dirs: ???
    horizon: ${horizon}
    n_obs_steps: ${n_obs_steps}
    pad_before: 2
    pad_after: 15
    split: train
    view: head_camera

policy:
  _target_: diffusion_policy.policy.robotwin_atm_diffusion_policy.RoboTwinATMDiffusionPolicy
  track_fn: ???
  track_view_key: head_cam
  track_task_key: track_task_emb
  shape_meta: *shape_meta
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    variance_type: fixed_small
    clip_sample: true
    prediction_type: epsilon
  obs_encoder:
    _target_: diffusion_policy.model.vision.multi_image_obs_encoder.MultiImageObsEncoder
    shape_meta: *shape_meta
    rgb_model:
      _target_: diffusion_policy.model.vision.model_getter.get_resnet
      name: resnet18
      weights: null
    resize_shape: null
    crop_shape: null
    random_crop: true
    use_group_norm: true
    share_rgb_model: false
    imagenet_norm: true
  horizon: ${horizon}
  n_action_steps: ${n_action_steps}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 100
  obs_as_global_cond: ${obs_as_global_cond}
  diffusion_step_embed_dim: 128
  down_dims: [256, 512, 1024]
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: true

ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: true
  pin_memory: true
  persistent_workers: false

val_dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: false
  pin_memory: true
  persistent_workers: false

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: cuda:0
  seed: 42
  debug: false
  resume: true
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 600
  gradient_accumulate_every: 1
  use_ema: true
  checkpoint_every: 300
  val_every: 1
  max_train_steps: null
  max_val_steps: null

hydra:
  run:
    dir: ./results/policy/${experiment}_${now:%m%d_%H%M}_s${training.seed}
